CREATE SET TABLE Informatica_Test.JobControl ,FALLBACK ,
    NO BEFORE JOURNAL,
    NO AFTER JOURNAL,
    CHECKSUM = DEFAULT,
    DEFAULT MERGEBLOCKRATIO,
    MAP = TD_MAP1
    (
    JobControlid INTEGER GENERATED ALWAYS AS IDENTITY
    (START WITH 1 
    INCREMENT BY 1 
    MINVALUE 1 
    MAXVALUE 2147483647 
    NO CYCLE),
    BatchCtrlID INTEGER,
    JobID INTEGER,
    StartDateTime TIMESTAMP(6),
    EndDateTime TIMESTAMP(6),
    RunID INTEGER,
    Status VARCHAR(30) CHARACTER SET LATIN NOT CASESPECIFIC FORMAT 'X(8)' NOT NULL,
    Success_Source_Rows INTEGER DEFAULT NULL,
    Target_Inserted_Rows INTEGER DEFAULT NULL,
    Target_Updated_Rows INTEGER DEFAULT NULL,
    Failed_Source_Rows INTEGER DEFAULT NULL,
    Failed_Target_Rows INTEGER DEFAULT NULL,
    ErrorMessage VARCHAR(1000) CHARACTER SET LATIN CASESPECIFIC)
    UNIQUE PRIMARY INDEX ( JobControlid );